### ISSUE TITLE
Input and Output Formatting

### ISSUE THREAD

**Issue by kapilace6** [TanishAggarwal5/coding_prep#11]
Comment Indentation
https://github.com/TanishAggarwal5/coding_prep/blob/cda4ef2be1b3c83d2c63437a250d9e29447ab653/cpp/Input_and_Output/code.cpp#L4-L17

Unnecessary Comment
https://github.com/TanishAggarwal5/coding_prep/blob/cda4ef2be1b3c83d2c63437a250d9e29447ab653/cpp/Input_and_Output/code.cpp#L19

**Comment by TanishAggarwal5** [comment]
fixed
