### ISSUE TITLE
Basic Data Types 

### ISSUE THREAD

**Issue by kapilace6** [TanishAggarwal5/coding_prep#5]
Indent comments
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/Basic%20Data%20Types/code.cpp#L1-L6

Indent comments
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/Basic%20Data%20Types/code.cpp#L27-L28

Blank Lines
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/Basic%20Data%20Types/code.cpp#L31-L32

**Comment by TanishAggarwal5** [comment]
fixed
