### ISSUE TITLE
Conditional Statements

### ISSUE THREAD

**Issue by kapilace6** [TanishAggarwal5/coding_prep#6]
Blank lines
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/Conditional%20Statements/code.cpp#L21

https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/Conditional%20Statements/code.cpp#L5-L8

Unnecessary Comment
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/Conditional%20Statements/code.cpp#L27-L29

**Comment by TanishAggarwal5** [comment]
fixed
