### ISSUE TITLE
For Loop

### ISSUE THREAD

**Issue by kapilace6** [TanishAggarwal5/coding_prep#7]
Unnecessary blank line..
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/For%20Loop/code.cpp#L27
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/For%20Loop/code.cpp#L22
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/For%20Loop/code.cpp#L29-L31

Spelling Error. `positive`
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/For%20Loop/code.cpp#L10

Comment indentation issue. Remove extra space at the beginning of line 19.
https://github.com/TanishAggarwal5/coding_prep/blob/bccb6611e4d27198e2a714f3f59670ed51947496/cpp/For%20Loop/code.cpp#L16-L19

**Comment by TanishAggarwal5** [comment]
fixed
