### ISSUE TITLE
Functions Formatting

### ISSUE THREAD

**Issue by kapilace6** [TanishAggarwal5/coding_prep#8]
Blank lines
https://github.com/TanishAggarwal5/coding_prep/blob/cda4ef2be1b3c83d2c63437a250d9e29447ab653/cpp/Functions/code.cpp#L23-L25

This else condition is not in {}, not in the same format as other conditions
https://github.com/TanishAggarwal5/coding_prep/blob/cda4ef2be1b3c83d2c63437a250d9e29447ab653/cpp/Functions/code.cpp#L22

Comment in L16 is not indented properly
https://github.com/TanishAggarwal5/coding_prep/blob/cda4ef2be1b3c83d2c63437a250d9e29447ab653/cpp/Functions/code.cpp#L12-L22

**Comment by TanishAggarwal5** [comment]
fixed
